### ISSUE TITLE
For other services

### ISSUE THREAD

**Issue by marcelloinfoweb** [candidtim/vagrant-appindicator#12]
Could I use it to monitor another service, for example, mysql or httpd (apache)?

Sorry English, I'm Brazilian. [Google Translate]

**Comment by candidtim** [comment]
Hello @marcelloinfoweb . If they run inside a VM managed by Vagrant, statuses of corresponding VMs can be reflected by vagrant-appindicator. However, it does not monitor any applications running inside the VM, but only reflects the status of the VM itself.
