### ISSUE TITLE
Feature: Different icon if vagrant is running

### ISSUE THREAD

**Issue by tr33m4n** [candidtim/vagrant-appindicator#4]
Hello there,

Just thought it would be a nice feature if the icon was different when one or more vagrants were up, could possibly help prevent data loss if it was more visual, so if the user running the vagrant had forgotten it was running and was about to shut down their computer

Cheers

**Comment by candidtim** [comment]
Thanks, that'll be nice indeed. I'm no designer, so icons are pretty simplistic, and I have several options now. Would be glad to have your feedback:
1. Simple "switched on light", smaller one
![vgindic-gree-light-small](https://cloud.githubusercontent.com/assets/8027970/5606225/1b41955a-9425-11e4-973a-6205b9c55110.png)
2. ... or a bigger one
![vgindic-green-light](https://cloud.githubusercontent.com/assets/8027970/5606224/1b3f4a84-9425-11e4-9851-3d39361d1dd9.png)
3. Or, like a led indicator on a server box
![vgindic-led-all](https://cloud.githubusercontent.com/assets/8027970/5606228/1b458e94-9425-11e4-92c0-50dbfcee13d8.png)
4. ... with this it can be used to indicate the number of active machines, until there are less than 4 of them
![vgindic-led-2](https://cloud.githubusercontent.com/assets/8027970/5606226/1b42e856-9425-11e4-938a-19f040a98624.png)
5. Same with smaller indicator lights
![vgindic-led-small](https://cloud.githubusercontent.com/assets/8027970/5606227/1b44e1b0-9425-11e4-9228-1783d007723d.png)

**Comment by tr33m4n** [comment]
I like the idea of number 4, but perhaps it'd be simpler if it was something like number 3. Either way 3, 4 and 5 have more of a visual impact than 1 and 2, personally they are my favorites :+1:

**Comment by candidtim** [comment]
This is now released in version 1.1.0. To update to the latest version, run the same command as for install:

    $ sudo pip install git+https://github.com/candidtim/vagrant-appindicator.git
